### ISSUE TITLE
Test security plugin

### ISSUE THREAD

**Issue by jmaupoux** [exanpe/exa-grails-plugins#1]

**Comment by lguerin** [comment]
First pass:

# Doc :

Add a section with plugin configuration (BuildConfig.groovy)

# NOCACHE :

OK

Cache-Control:no-cache
Cache-Control:no-store
Cache-Control:must-revalidate
Expires:Thu, 01 Jan 1970 00:00:00 GMT
Pragma:no-cache

Warning ZAP: 
Whenever possible ensure the cache-control HTTP header is set with no-cache, no-store, must-revalidate, private; and that the pragma HTTP header is set with no-cache.

# SERVER :

OK

Remote Address:127.0.0.1:8080
Request URL:http://localhost:8080/demo/
Request Method:GET
Status Code:200 OK

Server:My Blue server

# X-FRAME-OPTIONS :

This link is broken in the wiki page :
https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet

DENY => OK
SAMEORIGIN => OK
ALLOW-FROM => OK (with FF)

# COOKIES :

OK

web.xml:
    <cookie-config>
      <secure>true</secure>
      <name>MY_COOKIE</name>
    </cookie-config>

Run 'grails run-app -https':
Set-Cookie:MY_COOKIE=F0D8505748B06014C354DD49A589B5EF; Path=/demo/; Secure; HttpOnly

# REDIRECT :

OK

**Comment by jmaupoux** [comment]
Plugin conf added
Broken link fixed
