### ISSUE TITLE
Grails 3 repository not available

### ISSUE THREAD

**Issue by jromero-onclick** [exanpe/exa-grails-plugins#4]
I am trying to install the 2.0.0 version of the plugin in a grails 3.1.8 app and it seems that the repository is not available:

| Error Error initializing classpath: Could not find fr.exanpe.grails:exa-datatables:2.0.0.
Searched in the following locations:
    file:/Users/jordi/.m2/repository/fr/exanpe/grails/exa-datatables/2.0.0/exa-datatables-2.0.0.pom
    file:/Users/jordi/.m2/repository/fr/exanpe/grails/exa-datatables/2.0.0/exa-datatables-2.0.0.jar
    https://repo.grails.org/grails/core/fr/exanpe/grails/exa-datatables/2.0.0/exa-datatables-2.0.0.pom
    https://repo.grails.org/grails/core/fr/exanpe/grails/exa-datatables/2.0.0/exa-datatables-2.0.0.jar

**Comment by jromero-onclick** [comment]
I answer myself:

Add in build.gradle:

repositories {
    // Exanpe plugins
    maven { url "https://dl.bintray.com/exanpe/plugins" }
}

**Comment by lguerin** [comment]
You are right, the plugin is not yet available in the official grails plugins repository (status is pending validation).
To get the dependency, you can add the exanpe repository in the "repositories" section:

```
repositories {
    ...
    // Exanpe plugins
    maven { url "https://dl.bintray.com/exanpe/plugins" }
}
```
