### ISSUE TITLE
Datatables row grouping or jquery like accordion effect of row data

### ISSUE THREAD

**Issue by datamaskin** [exanpe/exa-grails-plugins#6]
Howdy, it would be very much appreciate a row grouping based on at least 1 column to accordion down the rows displaying only the row summary instead of the entire data rows based on a filtered column name.

**Comment by lguerin** [comment]
Hello,
I don't really understand what you would want to achieve.
Do you have a simplified example based on datatables.js for example?

**Comment by datamaskin** [comment]
Howdy Iguerin, thanks for the reply. I am using datatables Grails plugin directly for the reason it employs a so-called Child Rows API that uses a '+' character in the row comprising the accordioned child rows inside the 'parent' row. Problem solved. Thanks much.

**Comment by lguerin** [comment]
Ok, thanks for your feedback, I close the issue.
