### ISSUE TITLE
call grails3 controller from javascript to delete a row in the db

### ISSUE THREAD

**Issue by velo6raptor** [exanpe/exa-grails-plugins#8]
the $.post call doesn't work, the row is not deleted in DB, why ?

$(document).ready(function() {
				    var datatable = Exa.Datatable.getDatatable('tableDir');
				    
				    $('#tableDir tbody').on('click', '#delButton', function () {
				      var data = datatable.getInstance().row($(this).parents('tr')).data();
				      var deleteUrl = "${createLink(controller:'direction', action:'delete')}";

					  if ( confirm('Confirmez-vous la suppression de la direction '+data['code']+' ?') )
				    	$.post(deleteUrl, { directionId: data['id'] });
				    });
				});
and controller code

@Transactional
    def delete(long directionId) {

		def direction = Direction.get(directionId)
		
        if (direction == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        direction.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'direction.label', default: 'Direction'), direction.code])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

**Comment by lguerin** [comment]
I don't think this is related to the exa-datatables lib.
Have you check the "allowedMethods" settings of your controller delete method. Try to trigger your ajax request with a DELETE or a GET http verb.

**Comment by velo6raptor** [comment]
It works, thanks !
