### ISSUE TITLE
Change langage

### ISSUE THREAD

**Issue by velo6raptor** [exanpe/exa-grails-plugins#9]
I'd like to change the english labels search, show ... in french, how can i do ?

**Comment by lguerin** [comment]
Actually, the tag does not support i18n plugin provided by datatables.js lib, but you can set the labels like this (regarding the documentation https://datatables.net/reference/option/language) : 

```
<exa:datatable id="demo" items="${data}" auto="false"/>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    var datatable = Exa.Datatable.getDatatable('demo');
    var options = {
      language: {
        search: "Rechercher :",
        lengthMenu: "Afficher _MENU_ résultat(s)"
      }
    };
    datatable.render(options);
  });
</script>
```

**Comment by velo6raptor** [comment]
It Works ! thanks a lot, tell me when the plugin support i18n
